### ISSUE TITLE
File import format

### ISSUE THREAD

**Issue by ashenkin** [InverseTampere/qsm-blender-addons#1]
Hey Markku, thanks for putting this code out there.  It doesn't seem to want to import the .mat files, and i don't seem to get what I expect from cyl_files:
importing meshes seems to create a mesh in the scene, but i'm unable to view it in the blender window.
importing bezier's crashes on line 1123, bevel_object_name = scene['qsmBevelObject']

Can you give a bit more info about the file format the addon expects?

Thanks,
Allie

**Comment by peltokukka** [comment]
Hi Allie,

I added documentation in the README.md file. Hopefully, the input text file format is now clearer. The bevel object error is happening because you have not created and selected a bevel/lofting object. Please, see the documentation for that also. I'm planning to create error messages in Blender, to guide the user.

Cheers,

Markku
