### ISSUE TITLE
Blender 8.2

### ISSUE THREAD

**Issue by clevy2013** [InverseTampere/qsm-blender-addons#2]
I tried to use this with the new Blender 8.2, which appears to have rearranged the 3D toolbox location. This add-on did function for me with the old Blender 7.9.

![image](https://user-images.githubusercontent.com/58232811/82735615-f97ca100-9cf0-11ea-97fd-20f9053bb54c.png)

**Comment by peltokukka** [comment]
In short, this addon is yet to be upgraded to work with Blender 2.80 and newer. If you want to use it, you will have to use a version like 2.79.

This is because with the upgrade from 2.79 to 2.80 the python API of Blender was redesigned and thus the addon requires a lot of work, and I still haven't gotten to it.

**Comment by peltokukka** [comment]
Version 1.0.0 adds support for Blender 2.80 and up.
